server:
  host: "0.0.0.0"
  port: 8000
  debug: true

streaming:
  chunk_size: 4096
  sample_rate: 16000
  channels: 1

supported_languages:
  source: ["en", "fr", "es", "de"]
  target: ["en", "fr", "es", "de"]
