server:
  host: "0.0.0.0"
  port: 8000
  debug: true

  cors:
  origins: ["*"]
  credentials: true
  methods: ["*"]
  headers: ["*"]

streaming:
  chunk_size: 4096
  sample_rate: 16000
  buffer_size: 32768
  channels: 1
  supported_formats:
    - wav
    - mp3
    - ogg

translation:
  max_audio_length: 30  # seconds
  supported_languages:
    - en
    - es
    - fr
    - de
    - it
